package com.study.mapper.cluster;

import com.study.entity.cluster.City;
import com.study.entity.cluster.CityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcity
     *
     * @mbg.generated Mon Jun 05 15:32:47 CST 2017
     */
    long countByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcity
     *
     * @mbg.generated Mon Jun 05 15:32:47 CST 2017
     */
    int deleteByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcity
     *
     * @mbg.generated Mon Jun 05 15:32:47 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcity
     *
     * @mbg.generated Mon Jun 05 15:32:47 CST 2017
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcity
     *
     * @mbg.generated Mon Jun 05 15:32:47 CST 2017
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcity
     *
     * @mbg.generated Mon Jun 05 15:32:47 CST 2017
     */
    List<City> selectByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcity
     *
     * @mbg.generated Mon Jun 05 15:32:47 CST 2017
     */
    City selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcity
     *
     * @mbg.generated Mon Jun 05 15:32:47 CST 2017
     */
    int updateByExampleSelective(@Param("record") City record, @Param("example") CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcity
     *
     * @mbg.generated Mon Jun 05 15:32:47 CST 2017
     */
    int updateByExample(@Param("record") City record, @Param("example") CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcity
     *
     * @mbg.generated Mon Jun 05 15:32:47 CST 2017
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcity
     *
     * @mbg.generated Mon Jun 05 15:32:47 CST 2017
     */
    int updateByPrimaryKey(City record);
}