package com.study.entity.master;

public class Phone {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbphone.id
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbphone.phone_brand
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    private String phoneBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbphone.phone_name
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    private String phoneName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbphone.id
     *
     * @return the value of tbphone.id
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbphone.id
     *
     * @param id the value for tbphone.id
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbphone.phone_brand
     *
     * @return the value of tbphone.phone_brand
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public String getPhoneBrand() {
        return phoneBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbphone.phone_brand
     *
     * @param phoneBrand the value for tbphone.phone_brand
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public void setPhoneBrand(String phoneBrand) {
        this.phoneBrand = phoneBrand == null ? null : phoneBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbphone.phone_name
     *
     * @return the value of tbphone.phone_name
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public String getPhoneName() {
        return phoneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbphone.phone_name
     *
     * @param phoneName the value for tbphone.phone_name
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public void setPhoneName(String phoneName) {
        this.phoneName = phoneName == null ? null : phoneName.trim();
    }
}