package com.study.entity.master;

import java.util.ArrayList;
import java.util.List;

public class PhoneExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public PhoneExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandIsNull() {
            addCriterion("phone_brand is null");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandIsNotNull() {
            addCriterion("phone_brand is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandEqualTo(String value) {
            addCriterion("phone_brand =", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandNotEqualTo(String value) {
            addCriterion("phone_brand <>", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandGreaterThan(String value) {
            addCriterion("phone_brand >", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandGreaterThanOrEqualTo(String value) {
            addCriterion("phone_brand >=", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandLessThan(String value) {
            addCriterion("phone_brand <", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandLessThanOrEqualTo(String value) {
            addCriterion("phone_brand <=", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandLike(String value) {
            addCriterion("phone_brand like", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandNotLike(String value) {
            addCriterion("phone_brand not like", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandIn(List<String> values) {
            addCriterion("phone_brand in", values, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandNotIn(List<String> values) {
            addCriterion("phone_brand not in", values, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandBetween(String value1, String value2) {
            addCriterion("phone_brand between", value1, value2, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandNotBetween(String value1, String value2) {
            addCriterion("phone_brand not between", value1, value2, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneNameIsNull() {
            addCriterion("phone_name is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNameIsNotNull() {
            addCriterion("phone_name is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNameEqualTo(String value) {
            addCriterion("phone_name =", value, "phoneName");
            return (Criteria) this;
        }

        public Criteria andPhoneNameNotEqualTo(String value) {
            addCriterion("phone_name <>", value, "phoneName");
            return (Criteria) this;
        }

        public Criteria andPhoneNameGreaterThan(String value) {
            addCriterion("phone_name >", value, "phoneName");
            return (Criteria) this;
        }

        public Criteria andPhoneNameGreaterThanOrEqualTo(String value) {
            addCriterion("phone_name >=", value, "phoneName");
            return (Criteria) this;
        }

        public Criteria andPhoneNameLessThan(String value) {
            addCriterion("phone_name <", value, "phoneName");
            return (Criteria) this;
        }

        public Criteria andPhoneNameLessThanOrEqualTo(String value) {
            addCriterion("phone_name <=", value, "phoneName");
            return (Criteria) this;
        }

        public Criteria andPhoneNameLike(String value) {
            addCriterion("phone_name like", value, "phoneName");
            return (Criteria) this;
        }

        public Criteria andPhoneNameNotLike(String value) {
            addCriterion("phone_name not like", value, "phoneName");
            return (Criteria) this;
        }

        public Criteria andPhoneNameIn(List<String> values) {
            addCriterion("phone_name in", values, "phoneName");
            return (Criteria) this;
        }

        public Criteria andPhoneNameNotIn(List<String> values) {
            addCriterion("phone_name not in", values, "phoneName");
            return (Criteria) this;
        }

        public Criteria andPhoneNameBetween(String value1, String value2) {
            addCriterion("phone_name between", value1, value2, "phoneName");
            return (Criteria) this;
        }

        public Criteria andPhoneNameNotBetween(String value1, String value2) {
            addCriterion("phone_name not between", value1, value2, "phoneName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbphone
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 05 15:19:44 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbphone
     *
     * @mbg.generated Mon Jun 05 15:19:44 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}