package com.study.entity.master;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.id
     *
     * @mbg.generated Mon Jun 05 15:27:45 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.user_name
     *
     * @mbg.generated Mon Jun 05 15:27:45 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.age
     *
     * @mbg.generated Mon Jun 05 15:27:45 CST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.description
     *
     * @mbg.generated Mon Jun 05 15:27:45 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.id
     *
     * @return the value of tbuser.id
     *
     * @mbg.generated Mon Jun 05 15:27:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.id
     *
     * @param id the value for tbuser.id
     *
     * @mbg.generated Mon Jun 05 15:27:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.user_name
     *
     * @return the value of tbuser.user_name
     *
     * @mbg.generated Mon Jun 05 15:27:45 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.user_name
     *
     * @param userName the value for tbuser.user_name
     *
     * @mbg.generated Mon Jun 05 15:27:45 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.age
     *
     * @return the value of tbuser.age
     *
     * @mbg.generated Mon Jun 05 15:27:45 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.age
     *
     * @param age the value for tbuser.age
     *
     * @mbg.generated Mon Jun 05 15:27:45 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.description
     *
     * @return the value of tbuser.description
     *
     * @mbg.generated Mon Jun 05 15:27:45 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.description
     *
     * @param description the value for tbuser.description
     *
     * @mbg.generated Mon Jun 05 15:27:45 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}